### ISSUE TITLE
Postman issue

### ISSUE THREAD

**Issue by alerom114** [alerom114/SN15-tests#2]
How to implement the automated process in Postman?
AC: We should run the automated process on the Postman platform.

**Comment by brenrio** [comment]
In order to add the automated test process, we should use the pre-scripts in all cases.

**Comment by alerom114** [comment]
How to add the pre-script in Postman?

**Comment by brenrio** [comment]
We can use the Pre-script Tab in the postman.

**Comment by alerom114** [comment]
thx.
